CREATE DATABASE ExercicioPClinics_1_3;
GO

USE ExercicioPClinics_1_3;
GO

CREATE TABLE Clinica(
   IdClinica INT PRIMARY KEY IDENTITY(1,1),
   NomeClinca VARCHAR(20) NOT NULL UNIQUE,
   Endereco VARCHAR(40) UNIQUE,
   RazaoSocial VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Veterinario(
   IdVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
   IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
   NomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE Dono(
   IdDono SMALLINT PRIMARY KEY IDENTITY(1,1),
   NomeDono VARCHAR(20)
);
GO

CREATE TABLE PET(
   IdPet SMALLINT PRIMARY KEY IDENTITY(1,1),
   IdDono SMALLINT FOREIGN KEY REFERENCES Dono(IdDono),
   NomePet VARCHAR(20),
   IdRaca TINYINT FOREIGN KEY REFERENCES Raca(IdRaca)
);
GO

CREATE TABLE Atendimento(
    IdAtendimento INT PRIMARY KEY IDENTITY(1,1),
	IdPet SMALLINT FOREIGN KEY REFERENCES  PET(IdPet),
	IdVeterinario TINYINT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	NumeroAtendimento INT,
	DataAtendimento DATETIME2
);
GO

CREATE TABLE TipoPet(
  IdTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
  TipoPet VARCHAR(20)
);
GO

CREATE TABLE Raca(
  IdRaca TINYINT PRIMARY KEY IDENTITY(1,1),
  NomeRaca VARCHAR(20),
  IdTipoPet TINYINT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)
);
GO

ALTER TABLE Veterinario
ADD CRMV SMALLINT NOT NULL UNIQUE;

