CREATE DATABASE M_Rental_LIVIA
GO

USE M_Rental_LIVIA;
GO

CREATE TABLE Empresa(
   IdEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
   NomeEmpresa VARCHAR(50)
);
GO

CREATE TABLE Cliente(
  IdCliente INT PRIMARY KEY IDENTITY(1,1),
  NomeCliente VARCHAR(20) NOT NULL,
  SobrenomeCliente VARCHAR(50) NOT NULL,
  CPF CHAR(11) UNIQUE NOT NULL,
  DataNascimento DATE NOT NULL
);
GO

CREATE TABLE Marca(
  IdMarca TINYINT PRIMARY KEY IDENTITY(1,1),
  NomeMarca VARCHAR(20) UNIQUE
);
GO

CREATE TABLE Modelo(
  IdModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
  NomeModelo VARCHAR(20) NOT NULL,
  IdMarca TINYINT FOREIGN KEY REFERENCES Marca(IdMarca)
);
GO

CREATE TABLE Veiculo(
    IdVeiculo INT PRIMARY KEY IDENTITY(1,1),
	IdEmpresa  TINYINT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	Placa VARCHAR(20) UNIQUE,
	IdModelo SMALLINT FOREIGN KEY REFERENCES Modelo(IdModelo)
);
GO

CREATE TABLE Aluguel(
  IdAluguel INT PRIMARY KEY IDENTITY(1,1),
  IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
  IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo),
  Preco SMALLMONEY NOT NULL,
  [Data] DATETIME NOT NULL
);
GO

