CREATE DATABASE EXERCICIO_OPTUS_Livia;
GO

USE EXERCICIO_OPTUS_Livia;
GO

CREATE TABLE TipoUsuario(
   IdTipoUsuario INT PRIMARY KEY IDENTITY(1,1),
   TipoPermissoes VARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE Estilo(
   IdEstilo INT PRIMARY KEY IDENTITY(1,1),
   NomeEstilo VARCHAR(50) NOT NULL 
);
GO

CREATE TABLE Usuario(
   IdUsuario INT PRIMARY KEY IDENTITY(1,1),
   IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
   NomeUsuario VARCHAR(50) NOT NULL UNIQUE,
   Email VARCHAR(70) NOT NULL UNIQUE,
   Senha VARCHAR(50) NOT NULL 
);
GO

CREATE TABLE Artista(
   IdArtista INT PRIMARY KEY IDENTITY(1,1),
   IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
   NomeArtista VARCHAR(70) NOT NULL
);
GO

CREATE TABLE ALBUM(
  IdAlbum INT PRIMARY KEY IDENTITY(1,1),
  IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
  NomeAlbum VARCHAR(70) NOT NULL,
  DataLancamento DATE NOT NULL
);
GO

CREATE TABLE EstiloAlbum(
   IdEstiloAlbum INT PRIMARY KEY IDENTITY(1,1),
   IdAlbum INT FOREIGN KEY REFERENCES ALBUM(IdAlbum),
   IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
);
GO
